routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/rsud', function () {
    return view('frontend.rsud');
});

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('banner','BannerController');
Route::resource('role','UserRoleController');
Route::resource('modul','ModulController');
Route::resource('akses','AksesModulController');



Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController');
	Route::put('user/password', ['as' => 'user.password', 'uses' => 'UserController@password']);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);
});

app/AksesModul.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AksesModul extends Model
{
    protected $fillable = [
        'modul_id', 'user_role_id',
    ];

     public function Modul()
    {
        return $this->belongsTo(Modul::class);
    }
     public function UserRole()
    {
        return $this->belongsTo(UserRole::class);
    }
}

app/Http/Controllers/AksesModulController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\AksesModul;
use App\Modul;
use App\UserRole;

class AksesModulController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\User  $model
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $akses = AksesModul::paginate(10);
        $role = UserRole::all();

        return view('admin.akses_moduls.index', [
        'akses' => $akses,
        'role'=> $role,
        ]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
    	$akses = AksesModul::all();
        $modul = Modul::all();
        $user_role = UserRole::all();
        
        return view('admin.akses_moduls.create',[
            'modul'=>$modul,
            'user_role'=>$user_role,
            'akses'=>$akses,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        AksesModul::create($data);

        return redirect()->route('akses.index')->with('success','Akses Modul created successfully.');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // return view('banners.show',compact('id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Modul::findOrFail($id);

        return view('admin.moduls.edit', [
        'data' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $item = $request->all();

        $data = Modul::FindOrFail($id);
        
        $data->update($item);

        return redirect()->route('modul.index')->with('success','Edit successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Modul::FindOrFail($id);
        $data->delete();

        return redirect()->route('modul.index')->withInfo('Berhasil Di Hapus');
    }

    public function findByRole()
    {
    	$data = AksesModul::all();

    	return view('layouts.navbars.auth', [
        'data' => $data,
        ]);
    }
}

resources/views/admin/akses_moduls/create.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'akses_modul'
])

@section('content')
    <div class="content">
        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif
            <div class="col-md-12 text-center">
                <form class="col-md-12" action="{{ route('akses.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="card">
                        <div class="card-header">
                            <h5 class="title">{{ __('Create Akses Modul') }}</h5>
                        </div>
                        <div class="card-body">
                           <div class="row">
                                <label class="col-md-3 col-form-label">{{ __('Modul') }}</label>
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <select id="modul_id_id" name="modul_id" class="form-control">
                                            @foreach($modul as $item)
                                            <option value="{{$item->id}}">{{$item->modul}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    @if ($errors->has('modul_id'))
                                        <span class="invalid-feedback" style="display: block;" role="alert">
                                            <strong>{{ $errors->first('modul_id') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-md-3 col-form-label">{{ __('User Role') }}</label>
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <select id="user_role_id_id" name="user_role_id" class="form-control">
                                            @foreach($user_role as $item)
                                            <option value="{{$item->id}}">{{$item->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    @if ($errors->has('user_role_id'))
                                        <span class="invalid-feedback" style="display: block;" role="alert">
                                            <strong>{{ $errors->first('user_role_id') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        <div class="card-footer ">
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <button type="submit" class="btn btn-info btn-round">{{ __('Save') }}</button>
                                    <a href="{{route('akses.index')}}" class="btn btn-info btn-round" type="button">{{ __('Back') }}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/akses_moduls/index.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'akses_modul'
])

@section('content')

<div class="content">
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Akses Modul</h4>
                        <div class="row">
                            <div class="col-md-6">
                                <a href="{{route('akses.create')}}" type="button" style="text-decoration: none;" class="btn btn-sm btn-primary">Create</a>
                            </div>
                            <div class="col-md-6">
                            <form>
                                <div class="input-group no-border">
                                    <input type="text" value="" class="form-control" placeholder="Search...">
                                    <button class="input-group-append border-0" style="cursor: pointer;">
                                        <div class="input-group-text border-0">
                                            <i class="nc-icon nc-zoom-split"></i>
                                        </div>
                                    </button>
                                </div>
                            </form>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                    <tr>
                                        <th>
                                            No
                                        </th>
                                        <th>
                                            Modul
                                        </th>
                                        <th>
                                            Role
                                        </th>
                                        <th>
                                            Aksi
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($akses as $i => $item)
                                    <tr>
                                        <td>
                                            {{ ++$i + ($akses->currentPage()-1) * $akses->perPage() }}
                                        </td>
                                        <td>
                                            {{ $item->Modul->modul }}
                                        </td>
                                        <td>
                                            {{ $item->UserRole->name }}
                                        </td>
                                        <td class="text-center">
                                                <form action="{{ route('akses.destroy',$item->id) }}" method="POST">
                                 
                                                   <!--  <a class="btn btn-info btn-sm" href="{{ route('banner.show',$item->id) }}">Show</a> -->
                                 
                                                    <a class="btn btn-primary btn-sm" href="{{ route('akses.edit',$item->id) }}">Edit</a>
                                 
                                                    @csrf
                                                    @method('DELETE')
                                 
                                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                                                </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                             <div class="paginate text-center">
                                    {{ $akses->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection    